config/routes.rb
Rails.application.routes.draw do
  resources :bootstraps
   root 'bootstraps#index'

end

app/models/bootstrap.rb
class Bootstrap < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bootstraps_controller.rb
class BootstrapsController < ApplicationController
  before_action :set_bootstrap, only: [:show, :edit, :update, :destroy]

  # GET /bootstraps
  # GET /bootstraps.json
  def index
    @bootstraps = Bootstrap.all
  end

  # GET /bootstraps/1
  # GET /bootstraps/1.json
  def show
  end

  # GET /bootstraps/new
  def new
    @bootstrap = Bootstrap.new
  end

  # GET /bootstraps/1/edit
  def edit
  end

  # POST /bootstraps
  # POST /bootstraps.json
  def create
    @bootstrap = Bootstrap.new(bootstrap_params)

    respond_to do |format|
      if @bootstrap.save
        format.html { redirect_to @bootstrap, notice: 'Bootstrap was successfully created.' }
        format.json { render :show, status: :created, location: @bootstrap }
      else
        format.html { render :new }
        format.json { render json: @bootstrap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bootstraps/1
  # PATCH/PUT /bootstraps/1.json
  def update
    respond_to do |format|
      if @bootstrap.update(bootstrap_params)
        format.html { redirect_to @bootstrap, notice: 'Bootstrap was successfully updated.' }
        format.json { render :show, status: :ok, location: @bootstrap }
      else
        format.html { render :edit }
        format.json { render json: @bootstrap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bootstraps/1
  # DELETE /bootstraps/1.json
  def destroy
    @bootstrap.destroy
    respond_to do |format|
      format.html { redirect_to bootstraps_url, notice: 'Bootstrap was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bootstrap
      @bootstrap = Bootstrap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bootstrap_params
      params.require(:bootstrap).permit(:title, :fname, :lname, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstraps_helper.rb
module BootstrapsHelper
end

app/views/bootstraps/_form.html.erb
<%= form_for(@bootstrap) do |f| %>
  <% if @bootstrap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bootstrap.errors.count, "error") %> prohibited this bootstrap from being saved:</h2>

      <ul>
      <% @bootstrap.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bootstraps/edit.html.erb
<h1>Editing Bootstrap</h1>

<%= render 'form' %>

<%= link_to 'Show', @bootstrap %> |
<%= link_to 'Back', bootstraps_path %>

app/views/bootstraps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bootstraps</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Fname</th>
      <th>Lname</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bootstraps.each do |bootstrap| %>
      <tr>
        <td><%= bootstrap.title %></td>
        <td><%= bootstrap.fname %></td>
        <td><%= bootstrap.lname %></td>
        <td><%= bootstrap.rating %></td>
        <td><%= link_to 'Show', bootstrap %></td>
        <td><%= link_to 'Edit', edit_bootstrap_path(bootstrap) %></td>
        <td><%= link_to 'Destroy', bootstrap, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bootstrap', new_bootstrap_path %>

app/views/bootstraps/new.html.erb
<h1>New Bootstrap</h1>

<%= render 'form' %>

<%= link_to 'Back', bootstraps_path %>

app/views/bootstraps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bootstrap.title %>
</p>

<p>
  <strong>Fname:</strong>
  <%= @bootstrap.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @bootstrap.lname %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @bootstrap.rating %>
</p>

<%= link_to 'Edit', edit_bootstrap_path(@bootstrap) %> |
<%= link_to 'Back', bootstraps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bootstrapapp1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>